
angular.module('valintalaskenta')

   var KOODISTO_URL_BASE = KOODISTO_URL_BASE || "";

var SERVICE_URL_BASE = SERVICE_URL_BASE || "";
var TEMPLATE_URL_BASE = TEMPLATE_URL_BASE || "";
var VALINTAPERUSTEET_URL_BASE = VALINTAPERUSTEET_URL_BASE || "";
var SEURANTA_URL_BASE = SEURANTA_URL_BASE || "";
var DOKUMENTTIPALVELU_URL_BASE = DOKUMENTTIPALVELU_URL_BASE || "";
var VALINTALASKENTAKOOSTE_URL_BASE = VALINTALASKENTAKOOSTE_URL_BASE || "";
var VALINTALASKENTAKOOSTE_URL_BASE_HTTP = VALINTALASKENTAKOOSTE_URL_BASE.replace(/:\d{4}/, '') || "";
var TARJONTA_URL_BASE = TARJONTA_URL_BASE || "";
var SERVICE_EXCEL_URL_BASE = SERVICE_EXCEL_URL_BASE || "";
var SIJOITTELU_EXCEL_URL_BASE = SIJOITTELU_EXCEL_URL_BASE || "";
var HAKEMUS_URL_BASE = HAKEMUS_URL_BASE || "";
var ORGANISAATIO_URL_BASE = ORGANISAATIO_URL_BASE || "";
var ORGANIZATION_SERVICE_URL_BASE = ORGANISAATIO_URL_BASE || "/organisaatio-service/";
var HAKEMUS_UI_URL_BASE = HAKEMUS_UI_URL_BASE || "";
var VIESTINTAPALVELU_URL_BASE = VIESTINTAPALVELU_URL_BASE || "";
var CAS_URL = CAS_URL || "/cas/myroles";
var SIJOITTELU_URL_BASE = SIJOITTELU_URL_BASE || "";
var LOCALISATION_URL_BASE = LOCALISATION_URL_BASE || "";


