sudo: required

language: java

jdk:
- openjdk11

services:
- docker

cache:
  directories:
  - $HOME/.m2

env:
  global:
  # AWS_ACCESS_KEY_ID
  - secure: "eSiwmrp5TtUyhD8z3c6pDPrp2dS4jMZxbQf0mD/4mJfaiZHhSJ49cnikKeThxWlQx0597VV53hEtYAJOZUsDDtTGy0A/LbxkpZnWV0khzGeTE5qb9KW5FRBRZPJQzrOdalY/t8ajkJftkJhWRsewtPxWIHxPqiv2VsdwfhsFaQsCkfp5cgebjuF31/kTSnMZmrxdlT3eVRNdkSPT5SVGDIUV61VpYBDG7GkqrP83Ik8MAANBnjCrZQmkL1ScpiurBo/0gZqVp3l/aYA41HLmaX1C+xE4L9rSc4CusPEwCY8RL7ruUxwFU1NZYGa1toDpbY+c7i/LIL0HbcglySQy3xCNrUOyiBgUSv00DetHtLvR0UGo25lnMcnycbwgmibeRbepoYvAt5lattBNp9kmDYDDW4HCIOWp+vumZ3DEmYLg/UN/Gf1+oZUJ7hZmZdp4jt1v9DTfscf1IqMymbKCm+Vq4vFIxScHlsEdzZlBNYVDKAsjR1OSZLEto8TJ1vQdCv5LvDXDs7HpKc9Esm7nQyH0/HaQWzEo7kSOdTAkyinmNna1TMJH79hNwQHouzOjKdfHSam1BV03twDQHWUUOZatZcmW0zJ/djhy9h8lJEok3di5c6nALj0UTkeAEwp9Yvc8Fzebb102Ns8Ii3vhQwOlVZTsWgj35r4yCoPNTEQ="
  # AWS_SECRET_ACCESS_KEY
  - secure: "d5Hme557oLcT5N4cd1kOvRw0kydUCJpVyZufPLD0DHGGzF5MvbPb98Ec83+i0ZlLe7oDfxO6qSgPYpjJ68CN2aEjKIkr6LQRtQPqguy9oIRNNVjHn7SrswF1zV+6pms0lzyncFjFErQg3A+EsRctRHlha8RaKfRVRjfkxiQSdiRPkck3AfNJfAMiAzChn3nkIzNTpwqFDz0tFsvV430VVQsoXoHlgA56+0G5FnO+IbPCuPxtfyY3pfWdSEurvo9GLqzyDgj7fEIyTRFeHz1iOpWRtwM3FxU4GHNdFg9hStGR2/lhMVhQCxZ0g9ADE0WSq/XVy82nS9nKBkf9GTPPdtJ0ocqifFP52cafC2iorFpCoUtsXm8GfcGuc5ZRdQLlWh6L7l4uT130I46pYZvHLDPzpRG+nYlpb6AQO2gGSCeaAcxbwBV8iRFXOlJEpLZylCdyiWfVvLbOenIAczHf3mh+cKwkTiPQL+Pc/i+FSdasPhMkAhGWYkzVlQuv27t+twpXRdTVi8UwTjnksIqUzPAhjW+iOOJCLrPYKhEn9wGXWesE/1P/av2nNRgjEPnKjvvOpZBz2kVScGMC+r7b/SIQnPCB1Zm7aCZRgvYJu7xBFzv6AzZlveGutT/+sobP0gdmLAJkbTNaYWSPEpTsjCJiNAD7w4XMnudLJmTY0jo="

install:
- git clone https://github.com/Opetushallitus/ci-tools.git
- source ci-tools/common/setup-tools.sh
- sudo sh -c "printf '\n%s penaali.hard.ware.fi\n' $(dig +short artifactory.opintopolku.fi|head -n1) >> /etc/hosts"
- export ARTIFACT_NAME="valintalaskenta-ui"
- nvm install 10
- node -v
- npm -v
- npm install
- npm run build

script: >-
  ./bin/run-eslint-in-travis.sh &&
  ./bin/run-spotless-in-travis.sh &&
  mvn clean package -B -Dbranch=${TRAVIS_BRANCH} -Drevision=${TRAVIS_COMMIT} -DbuildNumber=${TRAVIS_BUILD_NUMBER} &&
  mv target/valintalaskenta-ui-*allinone.jar $DOCKER_BUILD_DIR/artifact/${ARTIFACT_NAME}.jar &&
  cp -vr src/main/resources/oph-configuration $DOCKER_BUILD_DIR/config/ &&
  export BASE_IMAGE="baseimage-fatjar-openjdk11:master" &&
  ./ci-tools/common/pull-image.sh &&
  ./ci-tools/build/build-fatjar.sh $ARTIFACT_NAME

deploy:
- provider: script
  script: ./ci-tools/build/upload-image.sh $ARTIFACT_NAME
  on:
    all_branches: true
