TEMPLATE_URL_BASE = "";
AUTH_MODE = "dev";
SESSION_KEEPALIVE_INTERVAL_IN_SECONDS = 1000000;
MAX_SESSION_IDLE_TIME_IN_SECONDS = 1000000;
SHOW_TILA_HAKIJALLE_IN_SIJOITTELUN_TULOKSET = "true";
READ_FROM_VALINTAREKISTERI = "false";
